events/urls.py
from django.conf.urls import patterns, url

from events import views

urlpatterns = patterns('',
    # ex: /events/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<event_id>\d+)/$', views.detail, name='detail'),
)

hrissite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hrissite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)+ staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^events/', include('events.urls')),
        #url(r'^contacts/', include('contacts.urls')),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT,
        'show_indexes': True}),
        url(r'',
        include('django.contrib.staticfiles.urls')),
                           
    ) + urlpatterns

contacts/models.py
from cms.models.pluginmodel import CMSPlugin
from django.db import models

# Create your models here.
class Contacts(models.Model):
	position_categories=(
	('Project Coordinator','Project Coordinator'),
	('Project Administrator','Project Administrator'),
	('System Analyst','System Analyst'),
	('System Developer','System Developer'),
	('Technical supervisor','Technical supervisor'),	
	)
	member_name=models.CharField(max_length=200)
	position=models.CharField(max_length=200, choices=position_categories , default='Project Coordinator')
	phone_number=models.CharField(max_length=15, blank=True)
	e_mail=models.EmailField(max_length=200,  blank=True)
	address=models.CharField(max_length=200,  blank=True)
	
	def __unicode__(self):   # Python 3: def __str__(self):
		return self.member_name
			
class ContactsPlugin(CMSPlugin):
	title=models.CharField(max_length=200, default='implementers')
	

downloads/models.py
from cms.models.pluginmodel import CMSPlugin
from django.db import models
from curses.ascii import NUL

# Create your models here.
class Downloads(models.Model):
    #download file
    file = models.FileField(upload_to='downloads')
    
    #a file title 
    file_title = models.CharField(max_length=200)
    
    #a download category
    DOWNLOAD_CAT = (
        ('Supportive supervision resources', 'Supportive supervision resources'),
        ('Training manuals and Documentations', 'Training manuals and Documentations'),
        ('HRHIS Tools and Resources', 'HRHIS Tools and Resources'),
    )
    category = models.CharField(max_length=50,
                                      choices=DOWNLOAD_CAT,
                                      default='Supportive supervision resources')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.file_title

class DownloadPlugin(CMSPlugin):
    title = models.CharField(max_length=200,default='my downloads')
    

events/models.py
from cms.models.pluginmodel import CMSPlugin
from django.db import models

# Create your models here.
class HR_events(models.Model): 
    event_name = models.CharField(max_length=200)
    event_discription = models.TextField(max_length=5000)
    event_date = models.DateField('date of event')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.event_name
    
class Event_photos(models.Model):
    event = models.ForeignKey('HR_events',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='events')
    title = models.CharField(max_length=200,null=True)
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.title
    
class EventPlugin(CMSPlugin):
    title = models.CharField(max_length=200,default='recent posts')

slideshow/models.py
from cms.models.pluginmodel import CMSPlugin
from django.db import models

# Create your models here.
class Slideshow(models.Model):
    image = models.ImageField(upload_to='carousel')
    desc_title = models.CharField(max_length=200,default='')
    desc_text = models.CharField(max_length=500,default='')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.desc_title

class SlideshowPlugin(CMSPlugin):
    title = models.CharField(max_length=200,default='my slide show')
    

events/views.py
# Create your views here.
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from events.models import *

def index(request):
    latest_events_list = HR_events.objects.order_by('-event_date')[:5]
    context = {'latest_events_list': latest_events_list}
    return render(request, 'events/index.html', context)

def detail(request, event_id):
    try:
        event = HR_events.objects.get(pk=event_id)
    except HR_events.DoesNotExist:
        raise Http404
    return render(request, 'events/details.html', {'event': event})
    

templates/base.html
{% load sekizai_tags i18n cms_tags menu_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang='en'>
	<head>
		<title >{% page_attribute page_title %}</title>
		<meta charset="utf-8">
		<meta http-equiv='refresh' content='60' >
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!--styles files-->
		<link rel="stylesheet" media='screen' href="{{STATIC_URL}}css/bootstrap.min.css" >
		<link rel="stylesheet" media='screen' href="{{STATIC_URL}}css/bootstrap-responsive.css" >
		<link rel="stylesheet" media='screen' href="{{STATIC_URL}}css/docs.css" >
		<link rel="stylesheet" media='screen' href="{{STATIC_URL}}css/prettify.css" >
		<link rel="stylesheet" media= 'screen' href="{{STATIC_URL}}css/style.css">
		<link rel="stylesheet" media= 'screen' href="{{STATIC_URL}}css/font-awesome/css/font-awesome.min.css">
		<link href="{{MEDIA_URL}}img/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	</head>
	
	<body align='center'>
		<div class="row-fluid btn btn-block">
			<div class="span1">
				
			</div>
			<div class="span10">
				<div class="row-fluid">
		 <div class="masthead">
		 	<img src="{{MEDIA_URL}}img/udsmlogo.jpg" class="pull-left img-circle" height="127" width="124">
            <img src="{{MEDIA_URL}}img/tanlogo.jpg" class="pull-left img-circle">
            
            <img src="{{MEDIA_URL}}img/jaicalogo.jpg" class="pull-left img-circle" height="127" width="124">
            <h2 style="color:#2a49d7;font-family: 'Bistro Script', Atrament "> Human Resource For Health Information System</h2>
            <div class="navbar" style="padding-top: 10px">
              <div class="navbar-inner" style="font-size: 0.9em">
                <div class="container" id="navs">
                  
                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </a>
                
                <!-- <a class="brand" href="{{BASE_URL}}" style="padding-left:30px">HRHIS</a> -->
				<div class="nav-collapse collapse">
					<ul class="nav"> 
						{% show_menu 0 100 100 100 "navigation.html" %}	
			        </ul>	
			    </div>
                </div>
              </div>
            </div><!-- /.navbar -->
          </div>
		
		</div>
			</div>
			<div class="span1">
				
			</div>
		</div>
		
		<div class=row-fluid>
			<div class="span1">
				
			</div>
			<div class="span10">
				
			
		
		<!--contents from other templates-->
		
		<!-- bradcumbs -->
			<div class ='row-fluid' >
				
				<!-- breadcrumbs-->
				<div class='row-fluid'id='breadcrumb-custom' >
					<ul class='breadcrumb' style='background-color:white; text-align:left'>
					{% show_breadcrumb %}
					<span class="pull-right"><em>{% now "jS F Y" %}</em></span>
					<form class="navbar-form form-search pull-right" action="search.php" method="post">
                        <div class="input-append">
                          <input type="text" class="span9 search-query" placeholder="Search" id="searchpeople" name="querystring">
                          <button type="submit" class="btn btn-primary" title="search" id="search-submit"><i class="icon-search icon-white"></i></button>
                        </div>
                    </form>
					</ul>
				</div>	
			</div>
			
			<!-- main content -->
			<div class ='row-fluid'>
				
				
					{% block contents %}{% endblock %}
				
			</div>
			<!--footer-->
			
			</div>
			<div class="span1">
				
			</div>
		</div>
		
		<div class='row-fluid'>
			
				<div class='btn btn-block btn-inverse' style="min-height: 200px">
					<div class="span1">
			</div>
			<div class="span10">
				<div class="span3 left" style="color: white;">
					
			
                        <div class="span2"><i class="icon-map-marker icon-3x pull-left"></i> </div>
                        <div class="span10 text-left"><h4>About HRHIS</h4>
                            <p><a href="/training" style="color: white;">Training</a></p>
                            <p><a href="/supervision" style="color: white;">Supervision</a></p>
                            <p><a href="/downloads" style="color: white;">Downloads</a></p>
                            <p><a href="/implemeters" style="color: white;">Implementers</a></p>
                    </div>
                    </div>
                    <div class="span3">
                        <div class="span2"><i class="icon-phone-sign icon-3x" ></i></div>
                        <div class="span10 text-left">Contacts
                        <address>
                        	<strong>The Coordinator,</strong><br />
                        	HISP Tanzania<br />
                        	Computer Science Unit<br />
                        	P.O BOX 35062 Dar es Salaam<br />
	                        <abbr title="Phone">P:</abbr> +255-22-2410500/9, +255-22-2410657, 255 784 147946<br>
	                        <a href="mailto:coordinator@hisptanzania.or.tz" style="color: white;"> coordinator@hisptanzania.or.tz</a>
                        </address></div>
                    </div>
                    <div class="span3" >
                        <div class="span2"><i class="icon-link icon-3x"></i>  </div>
                        <div class="span10 text-left">
                            <h4>Our Partners</h4>
                            <div style="padding-bottom: 6px"><a href="#" style="color: white;">JAICA</a></div>
                            <div style="padding-bottom: 6px"><a href="http://udsm.ac.tz" style="color: white;">UDSM</a></div>
                            <div style="padding-bottom: 6px"><a href="http://moh.go.tz/" style="color: white;">Ministry of Health & Social Welfare</a></div>
                            
                        </div>
                    </div>
                    <div class="span3 text-left">
                       <div style="padding-bottom: 10px"><a href ="#" style="color: white;"><i class="icon-facebook icon-2x "></i> Facebook </a> </div>
                       <div style="padding-bottom: 10px"><a href ="#" style="color: white;"><i class="icon-google-plus icon-2x"></i> Google-plus </a> </div>
                       <div style="padding-bottom: 10px"><a href ="#" style="color: white;"><i class="icon-twitter icon-2x "></i> Twitter </a> </div>
                       <div style="padding-bottom: 10px"><a href ="#" style="color: white;"><i class="icon-youtube icon-2x "></i> Youtube </a> </div>
                    </div>
				
				</div>
				<div class="span1">
					
				</div>
				</div>
				
		</div>
		<!--body of base template-->
		<!-- navigation bar-->
		
<!--js links for bootstrap-->
<script src="{{STATIC_URL}}js/jquery.js"></script>
<script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
<script>
$(document).reaady(function(){
	 $('#myCarousel').hide().carousel();
});
	
</script>
<script src="{{STATIC_URL}}js/holder.js"></script>
<script src="{{STATIC_URL}}js/prettify.js"></script>
<script src="{{STATIC_URL}}js/application.js"></script>
<!--end of js files from bootstrap-->	
    
		</body>
</html>

templates/contents.html
{% extends "base.html" %}
{% load cms_tags menu_tags %}
{% block contents %}
 <div class=row-fluid>
 	<div class='span9'>
 		{% block main_contents %} {% endblock %}
 	</div>
 	<div class='span3'>
 		{% block right_contents %} 
 		
 			<!-- <div id='news'>
				<h4>HRHIS Internals</h4>
				{% placeholder hrhis_internals or %} not yet added {% endplaceholder  %}
			</div>
			<!--news
			<div id='news'>
				<h4>Recent posts</h4>
				{% placeholder recent_post or %} not yet added {% endplaceholder  %}
			</div>
	
			<div id='news'>
				<h4>Usefull Links</h4>
				{% placeholder usefull_links or %} not yet added {% endplaceholder  %}
			</div>
			<div id='news'>
				<h4>Calendar</h4>
				{% placeholder calender or %} not yet added {% endplaceholder  %}
			</div> -->
	<div class="accordion" id="accordion2">
		  <div class="accordion-group" style="">
		    <div class="accordion-heading">
		      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
		        <img src="{{MEDIA_URL}}img/internal.jpg" class='img-circle'>
			   <b>HRHIS Internals</b>
		      </a>
		    </div>
		    <div id="collapseOne" class="accordion-body collapse">
		      <div class="accordion-inner">
		        {% placeholder hrhis_internals or %} not yet added {% endplaceholder  %}
		      </div>
		    </div>
		  </div>
		  
		  <div class="accordion-group">
		    <div class="accordion-heading">
		      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsethree">
		        <img src="{{MEDIA_URL}}img/recent.jpg" class='img-circle'>
			   <b>Recent Posts</b>
		      </a>
		    </div>
		    <div id="collapsethree" class="accordion-body collapse">
		      <div class="accordion-inner">
		        {% placeholder recent_post or %} not yet added {% endplaceholder  %}
		      </div>
		    </div>
		  </div>
		  
		  <div class="accordion-group">
		    <div class="accordion-heading">
		      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefour">
		        <img src="{{MEDIA_URL}}img/links.jpg" class='img-circle' height="150" width="150">
			   <b>Usefull Links</b>
		      </a>
		    </div>
		    <div id="collapsefour" class="accordion-body collapse">
		      <div class="accordion-inner">
		        <ul class="nav nav-tabs nav-stacked">
  					<li><a href="/downloads">Downloads</a></li>	
  					<li><a href="/events">Events</a></li>	
  					<li><a href="/supervision">Supervision</a></li>			
					<li><a href="/training">Training</a></li>
					<li><a href="http://moh.go.tz/">Ministry Of Health</a></li>
				</ul>
		      </div>
		    </div>
		  </div>
		  
		  <div class="accordion-group">
		    <div class="accordion-heading">
		      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefive">
		        <img src="{{MEDIA_URL}}img/soacial.jpg" class='img-circle' height="150" width="150">
			   <br><b>Social Medias</b>
		      </a>
		    </div>
		    <div id="collapsefive" class="accordion-body collapse">
		      <div class="accordion-inner">
		        <ul class="nav nav-tabs nav-stacked">
		        	<li><a href="#">Facebook</a></li>
  					<li><a href="#">Youtube</a></li>
  					<li><a href="#">Google Plus</a></li>
  					<li><a href="#">Linkedlin</a></li>
  					<li><a href="#">Rss Feed</a></li>
  					
				</ul>
		      </div>
		    </div>
		  </div>
		  <div class="accordion-group">
		    <div class="accordion-heading">
		      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
		        <img src="{{MEDIA_URL}}img/cal.jpg" class='img-circle' height="150" width="150">
			   <b>Callendar</b>
		      </a>
		    </div>
		    <div id="collapseTwo" class="accordion-body collapse">
		      <div class="accordion-inner">
		        {% placeholder calender or %} not yet added {% endplaceholder  %}
		      </div>
		    </div>
		  </div>
		</div>
 		{% endblock %}
 	</div>
 	<script>
	$(document).ready(function(){
		$("body").hide();
	});
</script>
 </div>

{% endblock %}

templates/dropdown_navigation.html
{% load menu_tags %}
{% for child in children %}
<li>
    <a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
    {% if child.children %}
    <ul class="dropdown">
        {% show_menu from_level to_level extra_inactive extra_active 'dropdown_navigation.html' "" "" child %}
    </ul>
    {% endif %}
</li>
{% endfor %}
   

templates/events/details.html
{% extends "contents.html" %}
{% load cms_tags menu_tags %}
{% block main_contents %}
<div class="well">
<h1 style="text-align: left;padding-bottom: 20px">{{ event.event_name|title}}</h1>

<p class="" style="text-align: left">{{event.event_discription}}</p>
{%if event.event_photos_set.all %} 
<h2 style="text-align: left">Events photos</h2>
<ul class="thumbnails">
{% for choice in event.event_photos_set.all %}	
  <li class="span6">
    <div class="thumbnail" >
      <img src="{{ choice.image.url }}" alt="" style="height: 100px">
      <p>{{ choice.title }} {{forloop.counter}}</p>
      
    </div>
  </li>
  {%if forloop.counter|divisibleby:"2" %}
  	</ul><ul class="thumbnails">	
  {% endif %}
  
{% endfor %}
</ul>
{% endif %}
</div>
{% endblock %}

templates/events/index.html
{% extends "contents.html" %}
{% load cms_tags menu_tags %}
{% block main_contents %}
<div class="well">

{% if latest_events_list %}
    <ul class="nav nav-stacked nav-tabs">
    {% for p in latest_events_list %}
        <li style="text-align: left; padding: 6px; border-bottom-width: 2px;border-bottom-color:blue"><a href="/events/{{ p.id }}/">
        	<strong class="lead"><i class="icon-th-large"></i> {{ p.event_name|title }} </strong>
        	<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{p.event_discription|truncatechars:59 }}
        	<b class="pull-right">{{p.event_date|date:"D d M Y"}}</b></a></li>
    {% endfor %}
    </ul>
    
{% else %}
    <h2>No Events are available.</h2>
{% endif %}
</div>
{% endblock %}

templates/home_page.html
{% extends "contents.html" %}
{% load cms_tags menu_tags %}
{% block main_contents %}
<!--slide shows and news-->
<div class='row-fluid'>
	<div class=''>
		<!--slide show-->
		
			<!--items for slide show-->
			<div class= 'row-fluid'>
				{% placeholder contents_for_other_page or %}not yet added{% endplaceholder  %}
			</div>
			
			<div class='row-fluid' style='text-align:left'>
				{% placeholder main-contents or %} not yet added {% endplaceholder  %}
			</div>
        </div>
        
        
	
</div>
<!--main contents-->
		

{% endblock %}

templates/navigation.html
{% load sekizai_tags i18n cms_tags menu_tags %}
{% load staticfiles %}

{% for child in children %}
					<li class="
					{% if child.selected %}active{% endif %}
					{% if child.ancestor %}ancestor{% endif %}
					{% if child.sibling %}sibling{% endif %}
					{% if child.descendant %}descendant{% endif %}
					{% if child.children %}dropdown{% endif %}
					 " style='font-size:1.2em'>
						{% if child.children %}
						<a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}" class="dropdown-toggle" data-toggle="dropdown">
							{{ child.get_menu_title }}
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							{% show_menu from_level to_level extra_inactive extra_active 'dropdown_navigation.html' "" "" child %}
						</ul>
						{% else %}
						<a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">
							{{ child.get_menu_title }}
						</a>
						{% endif %}
				
					</li>
					{% endfor %}
			

templates/pages/downloads.html
<div class="tabbable">
			<!--tabs for different articles-->
			<ul class ="nav nav-tabs">
				
				<li class="active span4"> <a href="#tab1" data-toggle='tab'> Supportive supervision resources</a></li>
				<li class="span4"> <a href="#tab2" data-toggle='tab'>Training manuals and Documentations</a></li>
				<li class="span4"> <a href="#tab3" data-toggle='tab'> HRHIS Tools and Resources </a></li>
			</ul>
			<!--contents for each tab-->
			<div class="tab-content" style="text-align: left">  
				<div class="tab-pane active" id="tab1">  
					<ul class="nav nav-tabs nav-stacked">
					{% for download in latest %}
						{% if download.category == 'Supportive supervision resources' %}
						<li style="padding: 3px"><a href="{{download.file.url}}"><b><i class="icon-file icon-white"></i> {{download.file_title}}</b> <i class="icon-download-alt pull-right"></i></a></li>
						{% endif%}
					{% endfor %}
					</ul>
				</div>  
				<div class="tab-pane" id="tab2">  
					<ul class="nav nav-tabs nav-stacked">
					{% for download in latest %}
						{% if download.category == 'Training manuals and Documentations' %}
						<li style="padding: 3px"><a href="{{download.file.url}}"><b><i class="icon-file icon-white"></i> {{download.file_title}}</b> <i class="icon-download-alt pull-right"></i></a></li>
						{% endif%}
					{% endfor %}
					</ul>
				</div>  
				<div class="tab-pane" id="tab3">  
					<ul class="nav nav-tabs nav-stacked">
					{% for download in latest %}
						{% if download.category == 'HRHIS Tools and Resources' %}
						<li style="padding: 3px"><a href="{{download.file.url}}"><b><i class="icon-file icon-white"></i> {{download.file_title}}</b> <i class="icon-download-alt pull-right"></i></a></li>
						{% endif%}
					{% endfor %}
					</ul>
			</div>  
		</div>	
	</div>

templates/pages/hello_plugin.html
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
  	
  	{% for image in latest %}
  	
  	{% if forloop.counter == 1 %}
  	<div class="active item">
  		<img src ='{{MEDIA_URL}}{{ image.image }}' style="height: 310px" class="img-polaroid img-rounded">
  		<div class="carousel-caption">
          <h4 style="text-align: left">{{ image.desc_title }}</h4>
          <p style="text-align: left">{{ image.desc_text }}</p>
        </div>
  	</div>
   	 
  	{% else%}
   	 <div class="item">
   	 	<img src ='{{MEDIA_URL}}{{ image.image }}' style="height: 310px" class="img-polaroid img-rounded">
   	 	<div class="carousel-caption">
          <h4 style="text-align: left">{{ image.desc_title }}</h4>
          <p style="text-align: left">{{ image.desc_text }}</p>
        </div>
   	 </div>
   	 {% endif%}
    {% endfor %}
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

templates/pages/implementers.html
{{conatcts.position}}
<p><strong>Project Coordinator:</strong></p>
{% for member in contacts %}
{% if member.position == 'Project Coordinator' %}
<p style="margin-left: 45px;">
<span>{{ member.member_name }}</span>
</p>
{% else %}
{% endif %}
{% endfor %}

<p><strong>Project Administrator:</strong></p>
{% for member in contacts %}
{% if member.position == 'Project Administrator' %}
<p style="margin-left: 45px;">
<span>&#160;{{ member.member_name }}</span>
</p>
{% else %}
{% endif %}
{% endfor %}

<p><strong>System Analyst:</strong></p>
{% for member in contacts %}
{% if member.position == 'System Analyst' %}
<p style="margin-left: 45px;">
<span>&#160;{{ member.member_name }}</span>
</p>
{% else %}
{% endif %}
{% endfor %}

<p><strong>System Developers:</strong></p>
{% for member in contacts %}
{% if member.position == 'System Developer' %}
<p style="margin-left: 45px;">
<span>&#160;{{ member.member_name }}</span>
</p>
{% else %}
{% endif %}
{% endfor %}

<p><strong>Technical supervisor:</strong></p>
{% for member in contacts %}
{% if member.position == 'Technical supervisor' %}
<p style="margin-left: 45px;">
<span>&#160;{{ member.member_name }}</span>
</p>
{% else %}
{% endif %}
{% endfor %}

templates/pages/recent_post.html
{% if latest %}
    {% for post in latest %}
    <div class="">
    	<p style="text-align: left;font-size: 1.1em;line-height: 12px"><a href="events/{{post.id}}" style="color:#0C566D;">
    		<i class="icon-bookmark"></i> {{post.event_name}}
    		</a>
    	</p>
    	<p style="text-align: left;font-size: 0.8em;line-height: 12px">{{post.event_discription|truncatechars:59}}</p>
    	<p style="text-align: right;line-height: 12px;color:#0C566D">{{post.event_date}} </p>
    </div>
    	<hr style="background-color: #8D8D8D"/>
    
    {% endfor %}
    <a href='/events/'>All Events</a>
{% else %}
    <h2>No Events are available.</h2>
{% endif %}

templates/twitter1.html
{% extends "contents.html" %}
{% load cms_tags menu_tags %}
{% block main_contents %}
<!--slide shows and news-->
<div class='row-fluid'>
	<div class=''>
		<!--slide show-->
		
			<!--items for slide show-->
			<div class= 'row-fluid'>
				{% placeholder contents_for_other_page or %}not yet added{% endplaceholder  %}
			</div>
			
			<div class='row-fluid' style='text-align:left'>
				{% placeholder main-contents or %} not yet added {% endplaceholder  %}
			</div>
        </div>
        
        
	
</div>
<!--main contents-->
		

{% endblock %}

templates/twitter2.html
{% extends "base2.html" %}
{% load cms_tags menu_tags %}
{% block contents %}

<!-- Two columns-->
<div class='around_two_column'>
<div class = 'row-fluid'>
<div class='span6'>
<!-- left column-->
<div id='left' >{% placeholder left or %} not yet added {% endplaceholder %}</div>
</div>
<div class= 'span6'>
<!-- right column-->
<div id='right'>{% placeholder right or %} not yet added {% endplaceholder%}</div>
</div>
</div>
</div>
{% endblock %}
<div class=">




</div>

templates/twitter3.html
{% extends "base2.html" %}
{% load cms_tags menu_tags %}
{% block contents %}
			

<div id='outer-row'>
<!--rows-->
<div id='rows'>
<div id='row1'>
<!--first row-->
{% placeholder first_row or %} not yet added {% endplaceholder %}
</div>
<div id='row2'>
<!--second row-->
{% placeholder second_row or %} not yet added {% endplaceholder %}
</div>
</div>
{% endblock %}

templates/twitter4.html
{% extends "base2.html" %}
{% load cms_tags menu_tags %}
{% block contents %}
				

<div class = 'row-fluid' id='three_columns'>
<!--three rows-->
<div class = 'span4' id='columns'>
<!--column-->
{% placeholder left_column or %} not yet added {% endplaceholder %}
</div>
<div class = 'span4' id='columns'>
<!--column-->
{% placeholder central_column or %} not yet added {% endplaceholder %}
</div>
<div class = 'span4' id='columns'>
<!--column-->
{% placeholder right_column or %} not yet added {% endplaceholder %}
</div>
</div>
{% endblock %}

templates/twitter5.html
{% extends "contents.html" %}
{% load cms_tags menu_tags %}
{% block main_contents %}
<div class= 'well' style="text-align: left">
{% placeholder contents_for_other_page or %}not yet added{% endplaceholder  %}
</div>

{% endblock %}